# SPDX-FileCopyrightText: 2020 Robert Cohn
#
# SPDX-License-Identifier: MIT

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: docs
        name: docs
        entry: make -C docs html
        language: system
        pass_filenames: false
        always_run: true
      - id: react-build
        name: react-build
        entry: bash -c "cd app/web && npm run build"
        language: system
        pass_filenames: false
        always_run: true
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: check-xml
    - id: check-yaml
    - id: check-case-conflict
    - id: check-toml
    - id: check-json
    - id: check-added-large-files
      args: ['--maxkb=800']

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8

-   repo: https://github.com/pycqa/doc8
    rev: master
    hooks:
    -   id: doc8

-   repo: https://github.com/pycqa/isort
    rev: develop
    hooks:
    -   id: isort

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
    -   id: clang-format

-   repo: https://github.com/fsfe/reuse-tool
    rev: master
    hooks:
    -   id: reuse
